function spec = executionSpec()
% detectViterbiPombeDivisionFrame.executionSpec  Pipeline contract.

spec = struct();
spec.summary = 'Tracks the pombe cell of interest by Viterbi and writes a mask plus septum profile/score dataseries.';

spec.staticKeys = { ...
    ... % Main settings.
    'anchorMode','anchorX','anchorY', ...
    'minArea','septumPolarity','stopAtSplit', ...
    ... % Frequent tracking/split corrections.
    'maxJumpCellDiameters','minTrackFrames', ...
    'splitAreaDropRatio','hardAreaDropRatio', ...
    'septumScoreThreshold', ...
    ... % Fine Viterbi tuning.
    'anchorFrames','anchorWeight', ...
    'distanceWeight','areaWeight','iouWeight', ...
    ... % Fine split detection.
    'splitRadiusCellDiameters', ...
    'splitCombinedAreaMinRatio','splitCombinedAreaMaxRatio', ...
    ... % Intensity profile settings.
    'profileSmoothBins','profileEdgeIgnoreFraction','profileBins', ...
    ... % Rarely changed implementation/diagnostic settings.
    'maxArea','inputMode','debug'};
spec.outputKeys = {'outputMaskChannelName','profileSeriesName','scoreSeriesName'};
spec.defaultImportKeys = {'instanceChannelName','rawChannelName','outputMaskChannelName'};
spec.defaults = rmfield(detectViterbiPombeDivisionFrame.setparam(struct()), 'tip');

spec.labels = struct( ...
    'instanceChannelName', 'Instance mask channel', ...
    'rawChannelName', 'Raw image channel', ...
    'outputMaskChannelName', 'Tracked cell mask output', ...
    'profileSeriesName', 'Intensity profile dataseries', ...
    'scoreSeriesName', 'Septum score dataseries', ...
    'anchorMode', 'Initial target selector', ...
    'anchorX', 'Custom target X position', ...
    'anchorY', 'Custom target Y position', ...
    'minArea', 'Minimum object area', ...
    'septumPolarity', 'Septum contrast polarity', ...
    'stopAtSplit', 'Stop mask after split', ...
    'maxJumpCellDiameters', 'Maximum tracking jump', ...
    'minTrackFrames', 'Minimum frames before split detection', ...
    'splitAreaDropRatio', 'Split area-drop ratio', ...
    'hardAreaDropRatio', 'Hard area-drop ratio', ...
    'anchorFrames', 'Initial anchor frames', ...
    'anchorWeight', 'Initial anchor weight', ...
    'distanceWeight', 'Distance continuity weight', ...
    'areaWeight', 'Area continuity weight', ...
    'iouWeight', 'Overlap continuity weight', ...
    'splitRadiusCellDiameters', 'Split search radius', ...
    'splitCombinedAreaMinRatio', 'Minimum daughter area ratio', ...
    'splitCombinedAreaMaxRatio', 'Maximum daughter area ratio', ...
    'profileSmoothBins', 'Profile smoothing bins', ...
    'profileEdgeIgnoreFraction', 'Ignored profile edge fraction', ...
    'profileBins', 'Longitudinal profile bins', ...
    'maxArea', 'Maximum object area', ...
    'inputMode', 'Mask interpretation', ...
    'septumScoreThreshold', 'Septum score threshold', ...
    'debug', 'Verbose diagnostics');

spec.tips = struct( ...
    'instanceChannelName', 'Labeled CellposeSAM instance mask channel, usually results_*_cell.', ...
    'rawChannelName', 'Raw or focused DIC channel used to compute the longitudinal septum profile.', ...
    'outputMaskChannelName', 'Binary ROI image channel for the selected cell of interest.', ...
    'profileSeriesName', 'Temporal dataseries with one row per frame and 100 normalized profile bins by default.', ...
    'scoreSeriesName', 'Temporal dataseries with the frame-wise septum score, binary septum detection, and tracking diagnostics.', ...
    'anchorMode', 'Select the expected initial cell position. right, left, and center use fixed coordinates; custom uses anchorX and anchorY.', ...
    'anchorX', 'Normalized X coordinate used only when the initial target selector is custom. Usually keep the default value.', ...
    'anchorY', 'Normalized Y coordinate used only when the initial target selector is custom. Usually keep the default value.', ...
    'minArea', 'Objects smaller than this pixel area are ignored. Increase it only when segmentation produces small debris.', ...
    'septumPolarity', 'Expected DIC septum contrast: dark, bright, or absolute.', ...
    'stopAtSplit', 'When enabled, the selected-cell output mask is zeroed after the detected split.', ...
    'maxJumpCellDiameters', 'Maximum allowed frame-to-frame centroid displacement, expressed in approximate cell diameters.', ...
    'minTrackFrames', 'Number of initial tracked frames required before split-stop detection can trigger.', ...
    'splitAreaDropRatio', 'Split candidate threshold based on the current area divided by the preceding tracked area.', ...
    'hardAreaDropRatio', 'Fallback split-stop threshold based on the current area divided by the early typical area.', ...
    'septumScoreThreshold', 'Threshold used only to create the septumDetected output column. max_valid_score frame selection does not use it.', ...
    'anchorFrames', 'Number of initial frames over which the expected target position contributes to the Viterbi cost. Usually keep the default value.', ...
    'anchorWeight', 'Weight of the initial-position cost. Usually keep the default value.', ...
    'distanceWeight', 'Weight of centroid displacement in the Viterbi transition cost. Usually keep the default value.', ...
    'areaWeight', 'Weight of area continuity in the Viterbi transition cost. Usually keep the default value.', ...
    'iouWeight', 'Weight of mask overlap continuity in the Viterbi transition cost. Usually keep the default value.', ...
    'splitRadiusCellDiameters', 'Search radius for daughter candidates around the preceding cell. Usually keep the default value.', ...
    'splitCombinedAreaMinRatio', 'Minimum accepted combined daughter-to-parent area ratio. Usually keep the default value.', ...
    'splitCombinedAreaMaxRatio', 'Maximum accepted combined daughter-to-parent area ratio. Usually keep the default value.', ...
    'profileSmoothBins', 'Moving-average window applied to the longitudinal profile before septum scoring. Usually keep the default value.', ...
    'profileEdgeIgnoreFraction', 'Fraction excluded at both ends of the profile during septum scoring. Usually keep the default value.', ...
    'profileBins', 'Number of normalized longitudinal profile bins stored in the output dataseries. Usually keep 100.', ...
    'maxArea', 'Objects larger than this pixel area are ignored. Inf disables the upper filter.', ...
    'inputMode', 'Interpret the instance input as auto, labeled, or binary. auto is recommended.', ...
    'debug', 'Print verbose tracking diagnostics. Keep disabled during normal runs.');

spec.choices = struct();

spec.contract = struct();
spec.contract.in = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('channels', 'channelSet', true, 'edge') ...
    ];
spec.contract.out = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('channels', 'channelSet', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', true, 'edge') ...
    ];
spec.contract.selectors = struct( ...
    'channelParam', 'instanceChannelName', ...
    'channelsParam', '', ...
    'framesParam', 'frames', ...
    'outputNameParam', 'outputMaskChannelName');
spec.contract.parameters = struct( ...
    'run', {{}}, ...
    'static', {spec.staticKeys}, ...
    'data', {{}});
spec.contract.requirements = struct();
spec.contract.requirements.roi = struct( ...
    'required', true, ...
    'channelsMin', 2, ...
    'dataSeries', false);
spec.contract.binding = struct( ...
    'scope', 'roi', ...
    'outputScope', 'roi', ...
    'mode', 'channelSlots', ...
    'selectorKeys', {{'instanceChannelName','rawChannelName'}}, ...
    'resolveAt', 'run', ...
    'exactCount', 2, ...
    'outputChannelNameParam', 'outputMaskChannelName');
spec.contract.capabilities = struct( ...
    'preservesRoiList', true, ...
    'roiChannels', true, ...
    'outputsChannels', true, ...
    'roiDataSeries', true, ...
    'outputsDataSeries', true, ...
    'roiMasks', false, ...
    'outputsMasks', false);
spec.contract.resources = struct();
spec.contract.resources.in = [ ...
    localResourceDef('channel', 'mask_roi_image', 'instanceChannelName', 'instanceChannelName', 'channels', 'instanceChannelName', true, ''), ...
    localResourceDef('channel', 'roi_image', 'rawChannelName', 'rawChannelName', 'channels', 'rawChannelName', true, '') ...
    ];
spec.contract.resources.out = [ ...
    localResourceDef('channel', 'cell_of_interest_mask', 'cell_of_interest', 'outputMaskChannelName', 'channels', 'outputMaskChannelName', false, 'roiChannel'), ...
    localResourceDef('dataSeries', 'division_profile', 'profile', 'profileSeriesName', 'dataSeries', 'profileSeriesName', false, 'roiDataSeries'), ...
    localResourceDef('dataSeries', 'division_score', 'score', 'scoreSeriesName', 'dataSeries', 'scoreSeriesName', false, 'roiDataSeries') ...
    ];
spec.contract.summary = spec.summary;
end

function p = localPortDef(name, type, required, source)
p = struct('name', name, 'type', type, 'required', logical(required), 'source', source);
end

function r = localResourceDef(type, role, symbol, param, port, nameParam, required, transfer)
r = struct( ...
    'type', type, ...
    'role', role, ...
    'symbol', symbol, ...
    'param', param, ...
    'port', port, ...
    'nameParam', nameParam, ...
    'required', logical(required), ...
    'transfer', transfer);
end
