function spec = executionSpec()
% detectViterbiPombeDivisionFrame.executionSpec  Pipeline contract.

spec = struct();
spec.summary = 'Tracks the pombe cell of interest by Viterbi and writes a mask plus septum profile/score dataseries.';

spec.staticKeys = { ...
    'inputMode','anchorMode','anchorX','anchorY','anchorFrames', ...
    'anchorWeight','distanceWeight','areaWeight','iouWeight', ...
    'maxJumpCellDiameters','minArea','maxArea','minTrackFrames', ...
    'splitAreaDropRatio','hardAreaDropRatio','splitRadiusCellDiameters', ...
    'splitCombinedAreaMinRatio','splitCombinedAreaMaxRatio','stopAtSplit', ...
    'profileBins','profileSmoothBins','profileEdgeIgnoreFraction', ...
    'septumPolarity','septumScoreThreshold','debug'};
spec.outputKeys = {'outputMaskChannelName','profileSeriesName','scoreSeriesName'};
spec.defaultImportKeys = {'instanceChannelName','rawChannelName','outputMaskChannelName'};
spec.defaults = rmfield(detectViterbiPombeDivisionFrame.setparam(struct()), 'tip');

spec.labels = struct( ...
    'instanceChannelName', 'Instance mask channel', ...
    'rawChannelName', 'Raw image channel', ...
    'outputMaskChannelName', 'Tracked cell mask output', ...
    'profileSeriesName', 'Intensity profile dataseries', ...
    'scoreSeriesName', 'Septum score dataseries', ...
    'anchorMode', 'Initial target selector', ...
    'septumPolarity', 'Septum contrast polarity', ...
    'septumScoreThreshold', 'Septum score threshold');

spec.tips = struct( ...
    'instanceChannelName', 'Labeled CellposeSAM instance mask channel, usually results_*_cell.', ...
    'rawChannelName', 'Raw or focused DIC channel used to compute the longitudinal septum profile.', ...
    'outputMaskChannelName', 'Binary ROI image channel for the selected cell of interest.', ...
    'profileSeriesName', 'Temporal dataseries with one row per frame and 100 normalized profile bins by default.', ...
    'scoreSeriesName', 'Temporal dataseries with the frame-wise septum score, binary septum detection, and tracking diagnostics.', ...
    'septumScoreThreshold', 'Threshold applied to septumScore to create the septumDetected output column.');

spec.choices = struct();

spec.contract = struct();
spec.contract.in = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('channels', 'channelSet', true, 'edge') ...
    ];
spec.contract.out = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('channels', 'channelSet', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', true, 'edge') ...
    ];
spec.contract.selectors = struct( ...
    'channelParam', 'instanceChannelName', ...
    'channelsParam', '', ...
    'framesParam', 'frames', ...
    'outputNameParam', 'outputMaskChannelName');
spec.contract.parameters = struct( ...
    'run', {{}}, ...
    'static', {spec.staticKeys}, ...
    'data', {{}});
spec.contract.requirements = struct();
spec.contract.requirements.roi = struct( ...
    'required', true, ...
    'channelsMin', 2, ...
    'dataSeries', false);
spec.contract.binding = struct( ...
    'scope', 'roi', ...
    'outputScope', 'roi', ...
    'mode', 'channelSlots', ...
    'selectorKeys', {{'instanceChannelName','rawChannelName'}}, ...
    'resolveAt', 'run', ...
    'exactCount', 2, ...
    'outputChannelNameParam', 'outputMaskChannelName');
spec.contract.capabilities = struct( ...
    'preservesRoiList', true, ...
    'roiChannels', true, ...
    'outputsChannels', true, ...
    'roiDataSeries', true, ...
    'outputsDataSeries', true, ...
    'roiMasks', false, ...
    'outputsMasks', false);
spec.contract.resources = struct();
spec.contract.resources.in = [ ...
    localResourceDef('channel', 'mask_roi_image', 'instanceChannelName', 'instanceChannelName', 'channels', 'instanceChannelName', true, ''), ...
    localResourceDef('channel', 'roi_image', 'rawChannelName', 'rawChannelName', 'channels', 'rawChannelName', true, '') ...
    ];
spec.contract.resources.out = [ ...
    localResourceDef('channel', 'cell_of_interest_mask', 'cell_of_interest', 'outputMaskChannelName', 'channels', 'outputMaskChannelName', false, 'roiChannel'), ...
    localResourceDef('dataSeries', 'division_profile', 'profile', 'profileSeriesName', 'dataSeries', 'profileSeriesName', false, 'roiDataSeries'), ...
    localResourceDef('dataSeries', 'division_score', 'score', 'scoreSeriesName', 'dataSeries', 'scoreSeriesName', false, 'roiDataSeries') ...
    ];
spec.contract.summary = spec.summary;
end

function p = localPortDef(name, type, required, source)
p = struct('name', name, 'type', type, 'required', logical(required), 'source', source);
end

function r = localResourceDef(type, role, symbol, param, port, nameParam, required, transfer)
r = struct( ...
    'type', type, ...
    'role', role, ...
    'symbol', symbol, ...
    'param', param, ...
    'port', port, ...
    'nameParam', nameParam, ...
    'required', logical(required), ...
    'transfer', transfer);
end
