function spec = executionSpec()
% bestFocusPlane.executionSpec  Pipeline contract for best-focus channel creation.

spec = struct();
spec.summary = 'Adds one ROI image channel containing the best focal plane selected independently per ROI and frame.';

spec.staticKeys = {'focusSmoothZ','focusProjectionRadius','focusCenterCrop','overwrite','verbose'};
spec.outputKeys = {'outputChannelName','zBestOutputName'};
spec.defaultImportKeys = {'channels','outputChannelName'};
spec.defaults = rmfield(bestFocusPlane.setparam(struct()), 'tip');

spec.labels = struct( ...
    'channels', 'Input z-stack channels', ...
    'outputChannelName', 'Best-focus channel', ...
    'zBestOutputName', 'Best-z dataseries', ...
    'focusSmoothZ', 'Z smoothing window', ...
    'focusProjectionRadius', 'Projection radius', ...
    'focusCenterCrop', 'Focus crop fraction');

spec.tips = struct( ...
    'channels', 'ROI channels interpreted as ordered z planes. Select DIC_Z001...DIC_Z100 for pomegranate data.', ...
    'outputChannelName', 'New ROI image channel used downstream for CNN/LSTM division timing.', ...
    'zBestOutputName', 'Temporal dataseries recording zBest plus raw and smoothed focus curves per ROI and frame.');

spec.choices = struct();

spec.contract = struct();
spec.contract.in = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('channels', 'channelSet', true, 'edge') ...
    ];
spec.contract.out = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('channels', 'channelSet', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', false, 'edge') ...
    ];
spec.contract.selectors = struct( ...
    'channelParam', '', ...
    'channelsParam', 'channels', ...
    'framesParam', 'frames', ...
    'outputNameParam', 'outputChannelName');
spec.contract.parameters = struct( ...
    'run', {{}}, ...
    'static', {spec.staticKeys}, ...
    'data', {{}});
spec.contract.requirements = struct();
spec.contract.requirements.roi = struct( ...
    'required', true, ...
    'channelsMin', 1, ...
    'dataSeries', false);
spec.contract.binding = struct( ...
    'scope', 'roi', ...
    'outputScope', 'roi', ...
    'mode', 'channelSet', ...
    'selectorKeys', {{'channels'}}, ...
    'resolveAt', 'run');
spec.contract.capabilities = struct( ...
    'preservesRoiList', true, ...
    'roiChannels', true, ...
    'outputsChannels', true, ...
    'roiDataSeries', true, ...
    'outputsDataSeries', true, ...
    'roiMasks', false, ...
    'outputsMasks', false);
spec.contract.resources = struct();
spec.contract.resources.in = localResourceDef('channel', 'roi_image', 'channels', 'channels', 'channels', 'channels', true, '');
spec.contract.resources.out = [ ...
    localResourceDef('channel', 'derived_roi_image', 'focus', 'outputChannelName', 'channels', 'outputChannelName', false, 'roiChannel'), ...
    localResourceDef('dataSeries', 'focus_z', 'dataSeries', 'zBestOutputName', 'dataSeries', 'zBestOutputName', false, 'roiDataSeries') ...
    ];
spec.contract.summary = spec.summary;
end

function p = localPortDef(name, type, required, source)
p = struct('name', name, 'type', type, 'required', logical(required), 'source', source);
end

function r = localResourceDef(type, role, symbol, param, port, nameParam, required, transfer)
r = struct( ...
    'type', type, ...
    'role', role, ...
    'symbol', symbol, ...
    'param', param, ...
    'port', port, ...
    'nameParam', nameParam, ...
    'required', logical(required), ...
    'transfer', transfer);
end
