function spec = executionSpec()
% singleCellOscillations.executionSpec  Pipeline contract for this plugin.

spec = struct();
spec.summary = 'Extracts detrended single-cell fluorescence oscillations and writes temporal normalized-cycle dataseries.';

spec.staticKeys = { ...
    'labelColumn','fluorescenceColumn','cellValueReducer', ...
    'frameStart','frameEnd','framePeriod','timeUnit', ...
    'baselineMethod','baselineWindow','baselineEndpoints', ...
    'cycleBoundaryMode','transitionFrom','transitionTo', ...
    'minCycleLength','maxCycleLength','normFrames','interpolationMethod','allowExtrapolation', ...
    'writeArtifacts','outputDir','workbookName','runId','verbose'};
spec.outputKeys = {'traceOutputName','normalizedCyclesOutputName','cycleMetadataOutputName'};
spec.defaultImportKeys = {'classification_data','fluorescence_data','fluorescenceColumn','framePeriod','timeUnit'};

spec.defaults = rmfield(singleCellOscillations.setparam(struct()), 'tip');

spec.labels = struct( ...
    'classification_data', 'Classification dataseries', ...
    'fluorescence_data', 'Fluorescence dataseries', ...
    'fluorescenceColumn', 'Fluorescence column', ...
    'traceOutputName', 'Detrended trace output', ...
    'normalizedCyclesOutputName', 'Normalized cycles output', ...
    'cycleMetadataOutputName', 'Cycle metadata output');

spec.tips = struct( ...
    'classification_data', 'Input dataseries produced by CNN/LSTM, typically div_1.', ...
    'fluorescence_data', 'Input dataseries produced by computeMetrics, typically channel_quantification.', ...
    'fluorescenceColumn', 'Signal to detrend and normalize by detected cell cycle.', ...
    'normalizedCyclesOutputName', 'Temporal dataseries containing all accepted cycles resampled on normalized intra-cycle time.');

spec.choices = struct();
spec.choices.cellValueReducer = {'mean','median','first','max','min'};
spec.choices.timeUnit = {'frames','s','min','h'};
spec.choices.baselineMethod = {'moving_mean','moving_median','none'};
spec.choices.baselineEndpoints = {'shrink','fill','legacy_discard'};
spec.choices.cycleBoundaryMode = {'label_transition'};
spec.choices.interpolationMethod = {'linear','pchip','spline','nearest'};

spec.contract = struct();
spec.contract.in = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', true, 'edge') ...
    ];
spec.contract.out = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', true, 'edge') ...
    ];
spec.contract.selectors = struct( ...
    'channelParam', '', ...
    'channelsParam', '', ...
    'outputNameParam', 'normalizedCyclesOutputName');
spec.contract.parameters = struct( ...
    'run', {{}}, ...
    'static', {spec.staticKeys}, ...
    'data', {{}});
spec.contract.requirements = struct();
spec.contract.requirements.roi = struct( ...
    'required', true, ...
    'channelsMin', 0, ...
    'dataSeries', true);
spec.contract.binding = struct( ...
    'scope', 'roi', ...
    'outputScope', 'roi', ...
    'mode', 'dataSeries', ...
    'selectorKeys', {{'classification_data','fluorescence_data'}}, ...
    'resolveAt', 'run');
spec.contract.capabilities = struct( ...
    'preservesRoiList', true, ...
    'roiDataSeries', true, ...
    'outputsDataSeries', true, ...
    'roiChannels', false, ...
    'outputsChannels', false, ...
    'roiMasks', false, ...
    'outputsMasks', false);
spec.contract.resources = struct();
spec.contract.resources.in = [ ...
    localResourceDef('dataSeries', 'classification', 'classification', 'classification_data', 'dataSeries', 'classification_data', true, ''), ...
    localResourceDef('dataSeries', 'metrics', 'metrics', 'fluorescence_data', 'dataSeries', 'fluorescence_data', true, '') ...
    ];
spec.contract.resources.out = [ ...
    localResourceDef('dataSeries', 'oscillation_trace', 'dataSeries', 'traceOutputName', 'dataSeries', 'traceOutputName', false, 'roiDataSeries'), ...
    localResourceDef('dataSeries', 'normalized_cycles', 'dataSeries', 'normalizedCyclesOutputName', 'dataSeries', 'normalizedCyclesOutputName', false, 'roiDataSeries'), ...
    localResourceDef('dataSeries', 'cycle_metadata', 'dataSeries', 'cycleMetadataOutputName', 'dataSeries', 'cycleMetadataOutputName', false, 'roiDataSeries') ...
    ];
spec.contract.summary = spec.summary;
end

function p = localPortDef(name, type, required, source)
p = struct('name', name, 'type', type, 'required', logical(required), 'source', source);
end

function r = localResourceDef(type, role, symbol, param, port, nameParam, required, transfer)
r = struct( ...
    'type', type, ...
    'role', role, ...
    'symbol', symbol, ...
    'param', param, ...
    'port', port, ...
    'nameParam', nameParam, ...
    'required', logical(required), ...
    'transfer', transfer);
end
