function spec = executionSpec()
% detecdivPomegranate.executionSpec  Pipeline contract.

spec = struct();
spec.summary = 'Reconstructs a Pomegranate-like 3D whole-cell mask from the selected pombe cell and stores cytometry in cell_information.userData.';

spec.staticKeys = {'frameSelectionMode','manualFrame', ...
    'voxelSizeXY','voxelSizeZ', ...
    'pomegranate_gapClosureSizePx','pomegranate_bandCoverageRadiusPx', ...
    'pomegranate_interpolationSmoothingPx','pomegranate_solidityThreshold', ...
    'pomegranate_roiMarginPx','pomegranate_segmentRadiusPaddingPx', ...
    'pomegranate_minSegmentRadiusPx','pomegranate_skeletonPruneIterations', ...
    'storeReconstructionMask','outputDir','writeCsv','writeExcel','writeQcImages','writeMosaicImage','mosaicFileName', ...
    'experimentName','debug'};
spec.outputKeys = {'cellInformationSeriesName'};
spec.defaultImportKeys = {'zStackChannelNames','cellMaskChannelName','scoreSeriesName','focusSeriesName','cellInformationSeriesName'};
spec.defaults = rmfield(detecdivPomegranate.setparam(struct()), 'tip');

spec.labels = struct( ...
    'zStackChannelNames', 'DIC/BF z-stack channels', ...
    'cellMaskChannelName', 'Cell of interest mask', ...
    'scoreSeriesName', 'Septum score dataseries', ...
    'focusSeriesName', 'Best-focus z dataseries', ...
    'cellInformationSeriesName', 'Cell information output', ...
    'outputDir', 'Output folder (empty = current project)', ...
    'frameSelectionMode', 'Measurement frame', ...
    'voxelSizeXY', 'XY pixel size', ...
    'voxelSizeZ', 'Z spacing', ...
    'pomegranate_gapClosureSizePx', 'Pomegranate gap closure', ...
    'pomegranate_bandCoverageRadiusPx', 'Pomegranate band coverage', ...
    'pomegranate_interpolationSmoothingPx', 'Pomegranate smoothing', ...
    'pomegranate_solidityThreshold', 'Pomegranate solidity threshold');

spec.tips = struct( ...
    'zStackChannelNames', 'Ordered DIC/BF z planes for the ROI. For pomegranate data this is usually DIC_Z001...DIC_Z100.', ...
    'cellMaskChannelName', 'Binary selected-cell mask produced by detectViterbiPombeDivisionFrame.', ...
    'scoreSeriesName', 'Temporal septum score dataseries used to pick the measurement frame.', ...
    'focusSeriesName', 'Best-focus z dataseries produced by bestFocusPlane; its zBest column selects the reconstruction mid-slice.', ...
    'cellInformationSeriesName', 'Non-temporal dataseries. Measurements, reconstructed mask and QC overlays are stored in userData.');
spec.tips.outputDir = 'Leave empty to write artifacts in the current DetecDiv project folder. Set a path only as a machine-specific override.';

spec.choices = struct();

spec.contract = struct();
spec.contract.in = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('channels', 'channelSet', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', true, 'edge') ...
    ];
spec.contract.out = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', true, 'edge') ...
    ];
spec.contract.selectors = struct( ...
    'channelParam', 'cellMaskChannelName', ...
    'channelsParam', 'zStackChannelNames', ...
    'framesParam', '', ...
    'outputNameParam', 'cellInformationSeriesName');
spec.contract.parameters = struct( ...
    'run', {{}}, ...
    'static', {spec.staticKeys}, ...
    'data', {{'zStackChannelNames','cellMaskChannelName','scoreSeriesName','focusSeriesName'}});
spec.contract.requirements = struct();
spec.contract.requirements.roi = struct( ...
    'required', true, ...
    'channelsMin', 2, ...
    'dataSeries', true);
spec.contract.binding = struct( ...
    'scope', 'roi', ...
    'outputScope', 'roi', ...
    'mode', 'channelSet', ...
    'selectorKeys', {{'zStackChannelNames'}}, ...
    'resolveAt', 'run');
spec.contract.capabilities = struct( ...
    'preservesRoiList', true, ...
    'roiChannels', true, ...
    'outputsChannels', false, ...
    'roiDataSeries', true, ...
    'outputsDataSeries', true, ...
    'roiMasks', false, ...
    'outputsMasks', false);
spec.contract.resources = struct();
spec.contract.resources.in = [ ...
    localResourceDef('channel', 'z_stack', 'zStackChannelNames', 'zStackChannelNames', 'channels', 'zStackChannelNames', true, ''), ...
    localResourceDef('channel', 'cell_of_interest_mask', 'cellMaskChannelName', 'cellMaskChannelName', 'channels', 'cellMaskChannelName', true, ''), ...
    localResourceDef('dataSeries', 'division_score', 'scoreSeriesName', 'scoreSeriesName', 'dataSeries', 'scoreSeriesName', true, ''), ...
    localResourceDef('dataSeries', 'focus_z', 'focusSeriesName', 'focusSeriesName', 'dataSeries', 'focusSeriesName', true, '') ...
    ];
spec.contract.resources.out = localResourceDef('dataSeries', 'cell_information', ...
    'cell_information', 'cellInformationSeriesName', 'dataSeries', 'cellInformationSeriesName', false, 'roiDataSeries');
spec.contract.summary = spec.summary;
end

function p = localPortDef(name, type, required, source)
p = struct('name', name, 'type', type, 'required', logical(required), 'source', source);
end

function r = localResourceDef(type, role, symbol, param, port, nameParam, required, transfer)
r = struct( ...
    'type', type, ...
    'role', role, ...
    'symbol', symbol, ...
    'param', param, ...
    'port', port, ...
    'nameParam', nameParam, ...
    'required', logical(required), ...
    'transfer', transfer);
end
