function spec = executionSpec()
% fociBurstStats.executionSpec  Pipeline contract for this external module.

spec = struct();
spec.summary = 'Computes foci burst intervals from ROI classification dataseries and writes ROI dataseries plus Excel artifacts.';

spec.staticKeys = { ...
    'groupID','dataIndex','framePeriod','timeUnit','nBins','normalization','xLim', ...
    'outputDir','workbookName','runId','writeExcel','writeFigures','resetRun','verbose'};
spec.outputKeys = {'outputName'};
spec.defaultImportKeys = {'groupID','framePeriod','timeUnit','outputDir','workbookName'};

spec.defaults = struct( ...
    'outputName', 'foci_burst_stats', ...
    'groupID', '', ...
    'dataIndex', 1, ...
    'framePeriod', 1, ...
    'timeUnit', 'frames', ...
    'nBins', 'auto', ...
    'normalization', 'count', ...
    'xLim', [], ...
    'outputDir', '', ...
    'workbookName', 'foci_burst_stats.xlsx', ...
    'runId', '', ...
    'writeExcel', true, ...
    'writeFigures', false, ...
    'resetRun', false, ...
    'verbose', true);

spec.labels = struct( ...
    'groupID', 'Classification dataseries', ...
    'outputName', 'Output dataseries name', ...
    'outputDir', 'Output folder', ...
    'workbookName', 'Excel workbook', ...
    'framePeriod', 'Frame period', ...
    'timeUnit', 'Time unit');

spec.tips = struct( ...
    'groupID', 'Input classification dataseries groupid. Empty means first classification dataseries in each ROI.', ...
    'outputName', 'Dataseries groupid written back into each ROI.', ...
    'outputDir', 'Folder where the Excel workbook, run state, and figures are written. Empty means the current project folder.', ...
    'workbookName', 'Excel workbook filename written directly under outputDir.', ...
    'framePeriod', 'Time interval between frames, expressed in timeUnit.', ...
    'timeUnit', 'Time unit label used in Excel and figures.');

spec.choices = struct();
spec.choices.timeUnit = {'frames','s','min','h'};
spec.choices.normalization = {'count','probability','pdf','cdf','countdensity'};

spec.contract = struct();
spec.contract.in = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', false, 'edge') ...
    ];
spec.contract.out = [ ...
    localPortDef('roiList', 'roiList', true, 'edge'), ...
    localPortDef('dataSeries', 'dataSeriesSet', true, 'edge') ...
    ];
spec.contract.selectors = struct( ...
    'channelParam', '', ...
    'channelsParam', '', ...
    'outputNameParam', 'outputName');
spec.contract.parameters = struct( ...
    'run', {{}}, ...
    'static', {spec.staticKeys}, ...
    'data', {{}});
spec.contract.requirements = struct();
spec.contract.requirements.roi = struct( ...
    'required', true, ...
    'channelsMin', 0, ...
    'dataSeries', true);
spec.contract.binding = struct( ...
    'scope', 'roi', ...
    'outputScope', 'roi', ...
    'mode', 'dataSeries', ...
    'selectorKeys', {{'groupID'}}, ...
    'resolveAt', 'run');
spec.contract.capabilities = struct( ...
    'preservesRoiList', true, ...
    'roiDataSeries', true, ...
    'outputsDataSeries', true, ...
    'roiChannels', false, ...
    'outputsChannels', false, ...
    'roiMasks', false, ...
    'outputsMasks', false);
spec.contract.resources = struct();
spec.contract.resources.in = localResourceDef('dataSeries', 'classification', ...
    'classification', 'groupID', 'dataSeries', 'groupID', false, '');
spec.contract.resources.out = localResourceDef('dataSeries', 'foci_stats', ...
    'dataSeries', 'outputName', 'dataSeries', 'outputName', false, 'roiDataSeries');
spec.contract.summary = spec.summary;
end

function p = localPortDef(name, type, required, source)
p = struct('name', name, 'type', type, 'required', logical(required), 'source', source);
end

function r = localResourceDef(type, role, symbol, param, port, nameParam, required, transfer)
r = struct( ...
    'type', type, ...
    'role', role, ...
    'symbol', symbol, ...
    'param', param, ...
    'port', port, ...
    'nameParam', nameParam, ...
    'required', logical(required), ...
    'transfer', transfer);
end
